package:
  name: quantlib-python
  version: 1.26
  
source:
  url: https://github.com/lballabio/QuantLib-SWIG/releases/download/QuantLib-SWIG-v1.26/QuantLib-SWIG-1.26.tar.gz

requirements:
  build:
    - autoconf
    - swig >=4.0.2
    - python >=3.9
    - numpy >=1.21.5
  run:
    - python

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib-SWIG/blob/master/LICENSE.TXT
  summary: "QuantLib-Python: Python binding for QuantLib"
